name: Cache CI

on:
  push:
  workflow_dispatch:

jobs:
  cache-job:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: cache-b88b72c
        id: cache-step
        uses: actions/cache@v4
        with:
          path: ~/.cache
          key: cache-b88b72c

      - name: prime-cache-b88b72c
        run: echo "Cache hit: ${{ steps.cache-step.outputs.cache-hit }}"
